# ... outros serviços ...

  # --- SERVIÇO DO FRONTEND (COM AJUSTE) ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # --- ADICIONE ESTA SEÇÃO ---
      args:
        VITE_API_URL: https://api.vitapersonal.newsnow.blog
      # -------------------------
    container_name: vitapersonal-frontend
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.vitapersonal-frontend.rule=Host(`vitapersonal.newsnow.blog`)"
      - "traefik.http.routers.vitapersonal-frontend.entrypoints=websecure"
      - "traefik.http.routers.vitapersonal-frontend.tls=true"
      - "traefik.http.routers.vitapersonal-frontend.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.vitapersonal-frontend.loadbalancer.server.port=80"