version: '3.8'

networks:
  traefik_default:
    external: true
  vitapersonal-net:
    driver: bridge

volumes:
  vitapersonal-mysql:
    external: true

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vitapersonal-backend
    restart: unless-stopped
    networks:
      - traefik_default
      - vitapersonal-net
    depends_on:
      - mysql
    env_file:
      - ./backend/.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.vitapersonal-api.rule=Host(`api.vitapersonal.newsnow.blog`)"
      - "traefik.http.routers.vitapersonal-api.entrypoints=websecure"
      - "traefik.http.routers.vitapersonal-api.tls=true"
      - "traefik.http.routers.vitapersonal-api.tls.certresolver=myresolver"
      - "traefik.http.services.vitapersonal-api.loadbalancer.server.port=3000"

  mysql:
    image: mysql:8.0
    container_name: vitapersonal-db
    restart: unless-stopped
    env_file:
      - ./mysql.env  # <-- MUDANÇA IMPORTANTE: Carrega as senhas daqui
    volumes:
      - vitapersonal-mysql:/var/lib/mysql
    networks:
      - vitapersonal-net